language: node_js

node_js:
  - 8

addons:
  chrome: stable

env:
  - CHROME_BIN=/usr/bin/google-chrome
  - DISPLAY=:99.0

before_script:
  - yarn bootstrap
  - sh -e /etc/init.d/xvfb start 
  - sleep 3
