dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - 8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version [version]
before_script:
  - yarn bootstrap
