dist: trusty

sudo: required

addons:
  apt:
    packages:
      - google-chrome-beta

language: node_js

node_js:
  - 8

env:
  - CHROME_BIN=/usr/bin/google-chrome-beta

before_script:
  - yarn bootstrap
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
